<!DOCTYPE html>
<html>
<head>
	<title>Privacy Policy</title>
	<style>
		*{
			margin:0;
	        padding:0;
	        box-sizing:border-box;
	        text-decoration:none;
	        list-style: none;
		}
		body{
		    font-family:sans-serif;
	        background-position: center;
	        background-size: cover;
	        background-color: #E5E8E8;
	        height:100%;
	        width: 100%;
        }
        nav .nav-bar .search-box{
	        display: none;
	    }
	    #pid{
    	color:#76717191;
    	font-size:12px;
    	padding-left:120px;
    	margin:15px 0;
	    }
	    main{
	    	width:100%;
	    	height:auto;
	    	background-color:white;
	    	margin-top:-5px;
	    	margin-bottom:10px;
	    	align-content: center;
	    }
	    main .privacy-policy{
	    	width:100%;
	    	max-width: 980px;
	    	height:auto;
	    	margin:20px auto;
	    	padding:90px 70px;
	    }
	    main .privacy-policy h1{
	    	text-align: center;
	    	font-size: 35px
	    	color:#000000cc;

	    }
	    main .privacy-policy p{
	    	color:#8b8585;
	    	/*font-weight: bold;*/
	    	font-size: 15px;
	    }
        @media only screen and (max-width: 800px) {
            #pid{
                 margin-top:-10px;
            }
        }
	    </style>
</head>
<body>
    <?php include('header.php'); ?>
     <p id="pid">Home / Privacy Policy</p> 
    <main>
      	<div class="privacy-policy">
      		<h1>PRIVACY POLICY</h1><br><br><br><br>
      		<p>
<h3>1. Introduction</h3><br>
<br>
welcome,<br>
<br>
Our Privacy Policy governs your visit to nearbyproductstore.com, and explains how we collect, safeguard and disclose information that results from your use of our Service.<br>
<br>
We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.<br>
<br>
Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).<br>
<br>
<h3>2. Definitions</h3><br>
<br>
SERVICE means the nearbyproductstore.com website operated by Lachoo.<br>
<br>
PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).<br>
<br>
USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).<br>
<br>
COOKIES are small files stored on your device (computer or mobile device).<br>
<br>
DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.<br>
<br>
DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.<br>
<br><br>
DATA SUBJECT is any living individual who is the subject of Personal Data.<br>
<br><br>
THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.<br>
<br><br>
3. Information Collection and Use<br>
<br>
We collect several different types of information for various purposes to provide and improve our Service to you.<br><br>

4. Types of Data Collected<br><br>

<h4>Personal Data</p></h4><br>
<br>
While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:<br>
<br>
0.1. Email address<br><br>

0.2. First name and last name<br><br>

0.3. Phone number<br><br>

0.4. Address, Country, State, Province, ZIP/Postal code, City<br><br>

0.5. Cookies and Usage Data<br><br>

We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
<br><br>
<h4>Usage Data</h4><br>
<br>
We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”).
<br><br>
This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
<br><br>
When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.
<br><br>
<h4>Location Data</h4>
<br><br>
We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.
<br><br>
You can enable or disable location services when you use our Service at any time by way of your device settings.
<br><br>
<h4>Tracking Cookies Data</h4>
<br><br>
We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
<br><br>
Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
<br><br>
You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
<br><br>
Examples of Cookies we use:
<br>
0.1. Session Cookies: We use Session Cookies to operate our Service.
<br><br>
0.2. Preference Cookies: We use Preference Cookies to remember your preferences and various settings.
<br><br>
0.3. Security Cookies: We use Security Cookies for security purposes.
<br><br><br>


Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
<br><br>
Lachoo will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
<br><br>
<h3>8. Disclosure of Data</h3>
<br><br>
We may disclose personal information that we collect, or you provide:
<br><br>
0.1. Disclosure for Law Enforcement.
<br><br>
Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
<br><br>
0.2. Business Transaction.
<br><br>
If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
<br><br>
0.3. Other cases. We may disclose your information also:
<br><br>
0.3.1. to our subsidiaries and affiliates;<br><br>

15. Children’s Privacy
<br><br>
Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).
<br><br>
We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
<br><br>
<h4>17. Contact Us</h4>
<br>
If you have any questions about this Privacy Policy, please contact us by email: xyz@gmail.com.</p>
        </div>
    </main>

    <?php include('footer.php');?>
</body>
</html>